import type { Recipe, RecipeTag } from './types';

export const RECIPE_TAGS: Record<RecipeTag, { label: string; emoji: string }> = {
  hizli: { label: 'Hızlı Pratik (15 dk)', emoji: '⚡' },
  firin: { label: 'Fırın & Hamur İşi', emoji: '🥐' },
  hafif: { label: 'Hafif & Sağlıklı', emoji: '🥗' },
  tatli: { label: 'Tatlı Krizleri', emoji: '🧁' },
  anne: { label: 'Anne Lezzeti', emoji: '👵' },
};

/** Etiket filtresi olarak gösterilecekler (anne lezzeti kaynakla zaten görünüyor) */
export const FILTER_TAGS: RecipeTag[] = ['hizli', 'firin', 'hafif', 'tatli'];

// ponytail: örnek veri; Supabase recipes tablosu bağlanınca kaldırılacak
export const MOCK_RECIPES: Recipe[] = [
  {
    id: 'r-pankek',
    title: 'Pofuduk Japon Pankeki',
    emoji: '🥞',
    description: 'Bulut gibi yumuşacık, kahvaltıların yıldızı.',
    minutes: 20,
    difficulty: 1,
    tags: ['tatli'],
    source: { type: 'instagram', url: 'https://www.instagram.com/reel/ornek1/' },
    tip: 'Beyazları kar haline gelene dek çırp, tavaya 1 tatlı kaşığı su damlatıp kapak ört.',
    cookedCount: 7,
    favorite: true,
    ingredients: [
      { name: 'yumurta', amount: '2 adet' },
      { name: 'süt', amount: '3 yemek kaşığı' },
      { name: 'un', amount: '4 yemek kaşığı' },
      { name: 'şeker', amount: '2 yemek kaşığı' },
    ],
    steps: [
      'Sarıları süt ve unla çırp.',
      'Beyazları şekerle kar haline getir.',
      'İkisini yavaşça birleştir.',
      'Kısık ateşte kapağı kapalı pişir.',
    ],
  },
  {
    id: 'r-kofte',
    title: 'Anne Köftesi & Patates',
    emoji: '🧆',
    description: 'Pazar sofralarının vazgeçilmezi, fırından mis gibi.',
    minutes: 35,
    difficulty: 3,
    tags: ['firin', 'anne'],
    source: { type: 'family' },
    tip: 'Annemin tarifiyle: harca 1 kaşık fazla tereyağı ve bir fiske kimyon ekleyip dolapta 20 dk beklet.',
    cookedCount: 14,
    favorite: true,
    ingredients: [
      { name: 'kıyma', amount: '500 gr' },
      { name: 'soğan', amount: '1 adet' },
      { name: 'patates', amount: '4 adet' },
      { name: 'tereyağı', amount: '1 yemek kaşığı' },
    ],
    steps: ['Harcı yoğur ve dinlendir.', 'Köfteleri şekillendir.', 'Patateslerle fırında 200°C pişir.'],
  },
  {
    id: 'r-balkabagi',
    title: 'Kremalı Balkabağı Çorbası',
    emoji: '🎃',
    description: 'Muskat kokulu, içini ısıtan kadife çorba.',
    minutes: 15,
    difficulty: 1,
    tags: ['hafif', 'hizli'],
    source: { type: 'tiktok', url: 'https://www.tiktok.com/@ornek/video/1' },
    tip: "TikTok'taki şef gibi rendelenmiş muskat cevizi ve bir diş taze zencefil ile blenderdan geçir.",
    cookedCount: 4,
    favorite: false,
    ingredients: [
      { name: 'balkabağı', amount: '500 gr' },
      { name: 'krema', amount: '100 ml' },
      { name: 'soğan', amount: '1 adet' },
    ],
    steps: ['Soğanı kavur.', 'Balkabağını ekleyip yumuşayana kadar haşla.', 'Krema ile blenderdan geçir.'],
  },
  {
    id: 'r-penne',
    title: 'Kremalı Mantarlı Penne',
    emoji: '🍝',
    description: 'Dolabındaki krema ve mantarları değerlendirmek için harika bir gün!',
    minutes: 20,
    difficulty: 1,
    tags: [],
    source: { type: 'manual' },
    cookedCount: 3,
    favorite: false,
    ingredients: [
      { name: 'mantar', amount: '250 gr' },
      { name: 'krema', amount: '200 ml' },
      { name: 'penne', amount: '300 gr' },
      { name: 'sarımsak', amount: '2 diş' },
    ],
    steps: ['Makarnayı haşla.', 'Mantar ve sarımsağı sotele.', 'Krema ekle, makarnayla karıştır.'],
  },
  {
    id: 'r-sebze',
    title: 'Fırında Baharatlı Sebze',
    emoji: '🥘',
    description: 'Kabak ve domatesleri fırında karamelize lezzete dönüştür.',
    minutes: 35,
    difficulty: 1,
    tags: ['firin', 'hafif'],
    source: { type: 'manual' },
    cookedCount: 2,
    favorite: false,
    ingredients: [
      { name: 'kabak', amount: '2 adet' },
      { name: 'domates', amount: '4 adet' },
      { name: 'fesleğen', amount: 'birkaç yaprak' },
      { name: 'zeytinyağı', amount: '3 yemek kaşığı' },
    ],
    steps: ['Sebzeleri doğra.', 'Baharat ve yağla harmanla.', '200°C fırında 30 dk pişir.'],
  },
  {
    id: 'r-mercimek',
    title: 'Mercimek Çorbası',
    emoji: '🍲',
    description: 'Tereyağlı, limonlu klasik; soğuk günlerin kurtarıcısı.',
    minutes: 30,
    difficulty: 1,
    tags: ['hafif', 'anne'],
    source: { type: 'family' },
    tip: 'Servis ederken üstüne pul biberli tereyağı gezdir.',
    cookedCount: 9,
    favorite: true,
    ingredients: [
      { name: 'mercimek', amount: '1 su bardağı' },
      { name: 'tereyağı', amount: '1 yemek kaşığı' },
      { name: 'soğan', amount: '1 adet' },
      { name: 'havuç', amount: '1 adet' },
    ],
    steps: ['Soğan ve havucu kavur.', 'Mercimek ve suyu ekle.', 'Pişince blenderdan geçir.'],
  },
  {
    id: 'r-tavuk',
    title: 'Kaşarlı Tavuk Sote',
    emoji: '🍳',
    description: 'Tek tavada pratik akşam yemeği.',
    minutes: 25,
    difficulty: 2,
    tags: [],
    source: { type: 'instagram', url: 'https://www.instagram.com/reel/ornek2/' },
    cookedCount: 1,
    favorite: false,
    ingredients: [
      { name: 'tavuk', amount: '400 gr' },
      { name: 'domates', amount: '2 adet' },
      { name: 'kaşar', amount: '100 gr' },
      { name: 'biber', amount: '2 adet' },
    ],
    steps: ['Tavuğu sotele.', 'Sebzeleri ekle.', 'Üstüne kaşar rendele, kapağı kapat.'],
  },
];
